# python3 algorithm_analysis.py deep_q_learning_continues_and_experience_replay

python3 algorithm_analysis.py double_deep_q_learning_continues_and_experience_replay

# python3 algorithm_analysis.py dueling_deep_q_learning_continues_and_experience_replay

